// <auto-generated />
using GastroWebsiteNew.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GastroWebsiteNew.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240524092152_seedupdateddata")]
    partial class seedupdateddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GastroWebsiteNew.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "lantaw.jpg",
                            Location = "Il Corso",
                            Name = "Lantaw",
                            Type = "Restaurant"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "tamp.jpg",
                            Location = "Paseo Arcenas, Banawa",
                            Name = "Tamp Cafe & Co",
                            Type = "Restaurant"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "scape.jpg",
                            Location = "AZON Residences, Roof Deck, M.L. Quezon National Highway, Lapu-Lapu City",
                            Name = "Scape Skydeck",
                            Type = "Restaurant"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "abaca.jpg",
                            Location = "Paseo Arcenas, Banawa",
                            Name = "Abaca Baking Company",
                            Type = "Cafe"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "pig.jpg",
                            Location = "G/F, MSY Tower, Negros Rd, Cebu City",
                            Name = "The Pig and Palm",
                            Type = "Restaurant"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "lighthouse.jpg",
                            Location = "General Maxilom Ave, Cebu City",
                            Name = "Lighthouse Restaurant",
                            Type = "Restaurant"
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "cafebai.jpeg",
                            Location = "Ouano Ave, cor C.D.Seno, Mandaue City",
                            Name = "Cafe Bai",
                            Type = "Cafe"
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "anzani.png",
                            Location = "Panorama Heights Nivel Hills, Cebu City",
                            Name = "Anzani Restaurant",
                            Type = "Restaurant"
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "cafetalk.jpg",
                            Location = "Escario Building, 731 N Escario St, Cebu City",
                            Name = "Cafe Talk Library",
                            Type = "Cafe"
                        });
                });

            modelBuilder.Entity("GastroWebsiteNew.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("GastroWebsiteNew.Models.Review", b =>
                {
                    b.HasOne("GastroWebsiteNew.Models.Place", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("GastroWebsiteNew.Models.Place", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
